version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: 
                name: "Install NPM Modules"
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run: 
                name: "Build"
                command: npm run build
    test:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: 
                name: "Install NPM Modules"
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run: 
                name: "Build"
                command: npm run build
            - run: 
                name: "Test"
                command: npm test
            - store_artifacts:
                path: coverage     
            - codecov/upload:
                file: coverage/*.json  
workflows:
    evalidate:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - develop
                            - master
            - test:
                filters:
                    branches:
                        only:
                            - develop
                            - master
                requires:
                    - build